Output demo.gif
Set Height 900
Set Shell zsh
Sleep 1.5s
Type "./cg --debug"
Enter
Sleep 1s
Type "d"
Sleep 1s
Type "http://crl.quovadisglobal.com/pkioprivservg1.crl"
Sleep 700ms
Enter
Sleep 1.5s
Type "j"
Sleep 300ms
Type "j"
Sleep 300ms
Type "j"
Sleep 300ms
Enter
Sleep 3.5s
Type "h"
Sleep 1s
Type "b"
Sleep 1s
Enter
Sleep 1s
Type "j"
Sleep 300ms
Type "j"
Sleep 300ms
Type "j"
Sleep 300ms
Enter
Sleep 4s
Type "h"
Sleep 1.5s
Type "q"
Sleep 1s

