name: release
on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: git fetch --prune --unshallow
      - name: setup dependencies
        uses: actions/setup-go@v5
      - name: setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}\n''GORELEASER_CURRENT_TAG='$(git describe --tags --abbrev=0)'\nGORELEASER_PREVIOUS_TAG='$( git tag --sort=-creatordate | grep -A 1 $(git describe --tags --abbrev=0) | tail -n 1) > .release-env
      - name: release dry run
        run: make release-dry-run
      - name: release publish
        run: make release