// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"database/sql"
	"time"
)

type CertificateRevocationList struct {
	ID         int64
	Name       string
	Signature  []byte
	ThisUpdate time.Time
	NextUpdate sql.NullTime
	Url        sql.NullString
	Raw        []byte
}

type RevokedCertificate struct {
	ID             int64
	Serialnumber   string
	RevocationDate time.Time
	Reason         string
	RevocationList int64
}
